### ISSUE TITLE
Make the editor resizable horizontally.

### ISSUE THREAD

**Issue by kirjs** [kirjs/ng2-codelab#19]

**Comment by kirjs** [comment]
Different people have different screens sizes and preferences, would be great to allow the users to resize the editor. 
https://github.com/kirjs/ng2-codelab/blob/f8ac1bdeb9928f3d8435d3250a019c2bdf291d71/src/app/editor/editor.component.ts
https://github.com/kirjs/ng2-codelab/tree/f8ac1bdeb9928f3d8435d3250a019c2bdf291d71/src/app/exercise

**Comment by UmaMoiseenko** [comment]
I can look into that during next weekend :)

**Comment by kirjs** [comment]
Hi Uma, thanks for volunteering!
I'm strongly considering looking into this myself before the next class on Dec 9th (this is the most requested feature). 

If I end up not being able to do this, would be amazing if you could help with it over the weekend. 
If I end up fixing this, let me know if you would be interested in finding some other fun feature to work on.

**Comment by kirjs** [comment]
Ended up just making it larger for now, all yours for the weekend :)

**Comment by UmaMoiseenko** [comment]
👍

**Comment by UmaMoiseenko** [comment]
It looks like I need to be added to contributors, otherwise I don't have correct access rights to push new branch. `Permission to kirjs/ng2-codelab.git denied to UmaMoiseenko.` .
Let me know once you added me, so I can issue pull request

**Comment by kirjs** [comment]
I won't have access to my laptop soon, what you can do is fork the repo and push into your fork, them GitHub will offer you to create a pull request

**Comment by UmaMoiseenko** [comment]
Sounds good, will try that

**Comment by kirjs** [comment]
Feel free to ping me with any questions, I have my laptop for the next few hours.

**Comment by kirjs** [comment]
Fixed, thanks Uma!
