### ISSUE TITLE
Allow the users to disable autorun

### ISSUE THREAD

**Issue by kirjs** [kirjs/ng2-codelab#21]

**Comment by kirjs** [comment]
Currently we just  debounce-run on changes. 
This means that if you think for a second while typing, it'll start running it and things will get slow. 
Would be great to have a manual run button and autorun checkbox instead.

**Comment by momoadeli** [comment]
@kirjs , I'm talking a stab at this. FYI. Plan is to create a simple 'autorun control' component/service duo (`autoruncontrol.component`/`autoruncontrol.service`). `autoruncontrol.service` will be made application-wide accessible as a singleton (in app.module.tc providers) and will be injected into `editor.component` constructor who will check whether autorun/debounce is ON or OFF. If it's OFF, it will emit new source 'value' when 'run' button inside the `autocontrol.component` is clicked. If autorun is ON, it will run as-is.  It seems the only place needing change is in `editor.component` (plus the new autoruncontrol .ts files). 
(Note, `autoruncontrol.component`, which contains run and checkbox buttons, manages `autoruncontrol.service` ON/OFF state.)

**Comment by kirjs** [comment]
Amazing! 
This is how it happens now:

[Starts here](https://github.com/kirjs/ng2-codelab/blob/d79a9e87252a11fd97fb627bc2ace086ca31bec5/src/app/editor/editor.component.ts#L46) -> [propagates here](https://github.com/kirjs/ng2-codelab/blob/d79a9e87252a11fd97fb627bc2ace086ca31bec5/src/app/exercise/exercise.component.ts#L22) -> [Dispatches here](https://github.com/kirjs/ng2-codelab/blob/d79a9e87252a11fd97fb627bc2ace086ca31bec5/src/app/state.service.ts#L98) -> [Gets handled here](https://github.com/kirjs/ng2-codelab/blob/d79a9e87252a11fd97fb627bc2ace086ca31bec5/src/app/reducers.service.ts#L60)

**Comment by kirjs** [comment]
Feel free to ping me if you have any questions

**Comment by momoadeli** [comment]
@kirjs , I've already dug up the workflow. I updated my comment.

**Comment by kirjs** [comment]
Hey Mo, 
Instead of creating a separate service, please add a reducer and use global state service to dispatch the event. 

Add an `autorun` field to global state [here](https://github.com/kirjs/ng2-codelab/blob/d79a9e87252a11fd97fb627bc2ace086ca31bec5/src/app/codelab/codelab-config.ts#L80) and toggle it with a reducer.  

The benefit of this would be allowing the user to save this setting on refresh, and also be included with the feedback.

Let me know if this makes sense. 

The component part looks good.

**Comment by momoadeli** [comment]
@kirjs , roger that.  BTW, depending on my time and your preference I was thinking of using ng-bootstrap for the `autoruncontrol.component` which might conflict with your goal of keeping the app 'light'.  Let me know how you'd like me to proceed and if you prefer I stick with straight html/css. Thanks!

**Comment by kirjs** [comment]
Let's keep it light, and not bring in any external libs for now.

**Comment by kirjs** [comment]
Can't figure out how to assign to you

**Comment by momoadeli** [comment]
@kirjs , perhaps because I cloned and not forked?  The former requires adding me as a 'contributor'. I will gladly fork if that lubes your gears.  Just let me know what you'd like.

**Comment by momoadeli** [comment]
@kirjs , I forked.

**Comment by momoadeli** [comment]
@kirjs ,  BTW, here's a link on how to to assign this to me ('momoadeli'): [https://help.github.com/articles/assigning-issues-and-pull-requests-to-other-github-users/](url)

**Comment by kirjs** [comment]
Fixed, thanks @momoadeli
